CREATE OR REPLACE DATABASE  RH_DEMO_DB;

GRANT OWNERSHIP ON DATABASE RH_DEMO_DB TO SCHEMACHANGE_ROLE;

CREATE OR REPLACE WAREHOUSE  RH_DEMO_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

GRANT OWNERSHIP ON WAREHOUSE RH_DEMO_WH TO SCHEMACHANGE_ROLE;