name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ DEV_SNOWFLAKE.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ DEV_SNOWFLAKE.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_ROLE: ${{ DEV_SNOWFLAKE.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ DEV_SNOWFLAKE.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ DEV_SNOWFLAKE.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ DEV_SNOWFLAKE.SNOWFLAKE_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange on $SNOWFLAKE_ACCOUNT"
          echo "schemachange --account $SNOWFLAKE_ACCOUNT --username $SNOWFLAKE_USERNAME --role $SNOWFLAKE_ROLE --warehouse $SNOWFLAKE_WAREHOUSE --database $SNOWFLAKE_DATABASE --directory $GITHUB_WORKSPACE/migrations"